/*
  # Insert all DNA attributes

  1. Changes
    - Inserts all 256 DNA attributes across the four worlds:
      - Physical World (0000-003F): 64 attributes
      - Social World (0040-007F): 64 attributes
      - Digital World (0080-00BF): 64 attributes
      - Spiritual World (00C0-00FF): 64 attributes

  2. Data Organization
    - Each attribute includes:
      - Unique ID (hex format)
      - World association
      - Category assignment
      - Name
      - Definition
      - Description

  3. Notes
    - Uses existing category IDs from previous migration
    - Maintains consistent format across all attributes
    - Preserves existing data through ON CONFLICT clause
*/

-- Insert Physical World DNA attributes (0000-003F)
INSERT INTO dna_attributes (id, world_id, category_id, name, definition, description) VALUES
  ('0000', 'physical', get_category_id('physical', 'Basic Metrics'), 'Humanity Index', 'Measures the authenticity and credibility of user identity', 'Determines if the user is a real human or an automated bot using behavioral and biometric data'),
  ('0001', 'physical', get_category_id('physical', 'Physical Abilities'), 'Physical Fitness Score', 'Evaluates overall physical health', 'Uses movement data, biometrics, and exercise frequency to assess fitness'),
  ('0002', 'physical', get_category_id('physical', 'Physical Response'), 'Click Speed', 'Measures reaction speed and hand-eye coordination', 'Calculates the number of clicks per second in a test'),
  ('0003', 'physical', get_category_id('physical', 'Basic Metrics'), 'Earth Coordinates', 'Records the users primary geographic location', 'Tracks the home or frequently visited location for analytical purposes'),
  ('0004', 'physical', get_category_id('physical', 'Body Composition'), 'Body Mass Index', 'Measures body weight in relation to height', 'Assesses obesity, underweight, and overall health risks'),
  ('0005', 'physical', get_category_id('physical', 'Sensory Systems'), 'Visual Acuity', 'Evaluates vision clarity', 'Measures the users ability to see fine details at a distance'),
  ('0006', 'physical', get_category_id('physical', 'Sensory Systems'), 'Hearing Ability', 'Measures auditory perception', 'Evaluates sound detection levels and speech clarity'),
  ('0007', 'physical', get_category_id('physical', 'Vital Functions'), 'Sleep Patterns', 'Analyzes sleep quality and duration', 'Tracks sleep consistency, deep sleep percentage, and interruptions'),
  ('0008', 'physical', get_category_id('physical', 'Health Status'), 'Dietary Habits', 'Monitors eating preferences and consumption patterns', 'Identifies nutrition quality and food intake frequency'),
  ('0009', 'physical', get_category_id('physical', 'Vital Functions'), 'Heart Rate Variability', 'Measures the variation in time intervals between heartbeats', 'Reflects autonomic nervous system activity and stress levels'),
  ('000A', 'physical', get_category_id('physical', 'Physical Response'), 'Physical Reaction Time', 'Measures the speed of physical responses', 'Evaluates reflexes in response to stimuli'),
  ('000B', 'physical', get_category_id('physical', 'Vital Functions'), 'Blood Pressure', 'Records systolic and diastolic pressure', 'Identifies risks of hypertension or cardiovascular conditions'),
  ('000C', 'physical', get_category_id('physical', 'Body Systems'), 'Glucose Level', 'Tracks blood sugar levels', 'Evaluates metabolic health and diabetes risk'),
  ('000D', 'physical', get_category_id('physical', 'Body Systems'), 'Cholesterol Level', 'Measures total cholesterol in the blood', 'Assesses cardiovascular health risks'),
  ('000E', 'physical', get_category_id('physical', 'Body Systems'), 'Immune System Strength', 'Evaluates the bodys ability to fight infections', 'Assesses immune response efficiency based on historical health data'),
  ('000F', 'physical', get_category_id('physical', 'Health Status'), 'Skin Health', 'Measures skin condition and appearance', 'Tracks hydration, elasticity, and signs of aging'),
  ('0010', 'physical', get_category_id('physical', 'Physical Abilities'), 'Physical Endurance', 'Evaluates stamina during prolonged activities', 'Measures aerobic capacity through performance metrics'),
  ('0011', 'physical', get_category_id('physical', 'Physical Abilities'), 'Flexibility', 'Assesses the range of motion in joints and muscles', 'Determines how easily the body adapts to different positions'),
  ('0012', 'physical', get_category_id('physical', 'Physical Abilities'), 'Strength Level', 'Measures muscular power and resistance', 'Evaluates maximum weight lifting capability'),
  ('0013', 'physical', get_category_id('physical', 'Physical Abilities'), 'Coordination', 'Assesses motor control and movement precision', 'Measures hand-eye synchronization'),
  ('0014', 'physical', get_category_id('physical', 'Physical Abilities'), 'Balance', 'Evaluates stability while standing or moving', 'Measures the ability to maintain posture under different conditions'),
  ('0015', 'physical', get_category_id('physical', 'Physical Abilities'), 'Agility', 'Assesses speed and quickness of movements', 'Determines the users ability to change direction efficiently'),
  ('0016', 'physical', get_category_id('physical', 'Physical Abilities'), 'Stamina', 'Evaluates sustained energy output over time', 'Measures fatigue resistance during extended physical activity'),
  ('0017', 'physical', get_category_id('physical', 'Vital Functions'), 'Oxygen Saturation', 'Measures blood oxygen levels', 'Determines respiratory and circulatory system efficiency'),
  ('0018', 'physical', get_category_id('physical', 'Vital Functions'), 'Body Temperature', 'Records core body temperature', 'Monitors deviations that indicate illness or external temperature adaptation'),
  ('0019', 'physical', get_category_id('physical', 'Physical Response'), 'Pain Tolerance', 'Assesses endurance to physical discomfort', 'Measures resistance to pain stimuli'),
  ('001A', 'physical', get_category_id('physical', 'Health Status'), 'Injury History', 'Tracks past injuries and recovery status', 'Records history of fractures, muscle strains, and rehabilitation progress'),
  ('001B', 'physical', get_category_id('physical', 'Physical Response'), 'Recovery Rate', 'Measures how quickly the body recovers from fatigue or injuries', 'Evaluates post-exercise heart rate recovery and muscle healing speed'),
  ('001C', 'physical', get_category_id('physical', 'Body Systems'), 'Metabolic Rate', 'Calculates the rate at which the body burns calories', 'Determines daily energy expenditure'),
  ('001D', 'physical', get_category_id('physical', 'Body Systems'), 'Hydration Level', 'Measures body water content', 'Tracks hydration balance for optimal health'),
  ('001E', 'physical', get_category_id('physical', 'Body Composition'), 'Bone Density', 'Evaluates bone strength and mineral content', 'Assesses risk factors for osteoporosis'),
  ('001F', 'physical', get_category_id('physical', 'Body Composition'), 'Muscle Mass', 'Records muscle tissue proportion', 'Determines the balance between muscle and fat'),
  ('0020', 'physical', get_category_id('physical', 'Body Composition'), 'Fat Percentage', 'Measures body fat ratio', 'Identifies health risks related to excess fat storage'),
  ('0021', 'physical', get_category_id('physical', 'Body Systems'), 'Cardiovascular Health', 'Assesses heart and blood vessel functionality', 'Uses heart rate, cholesterol, and blood pressure data'),
  ('0022', 'physical', get_category_id('physical', 'Body Systems'), 'Respiratory Health', 'Evaluates lung function', 'Measures oxygen intake and lung capacity'),
  ('0023', 'physical', get_category_id('physical', 'Body Systems'), 'Neurological Health', 'Measures nervous system efficiency', 'Evaluates brain and nerve signal response speed'),
  ('0024', 'physical', get_category_id('physical', 'Body Systems'), 'Digestive Health', 'Assesses gut functionality', 'Tracks digestion speed, food absorption, and gut flora balance'),
  ('0025', 'physical', get_category_id('physical', 'Body Systems'), 'Liver Function', 'Evaluates liver enzyme levels', 'Determines toxin processing efficiency'),
  ('0026', 'physical', get_category_id('physical', 'Body Systems'), 'Kidney Function', 'Measures filtration efficiency of kidneys', 'Evaluates toxin removal and hydration regulation'),
  ('0027', 'physical', get_category_id('physical', 'Body Systems'), 'Hormonal Balance', 'Monitors endocrine hormone levels', 'Assesses potential hormonal imbalances affecting mood, metabolism, and energy'),
  ('0028', 'physical', get_category_id('physical', 'Sensory Systems'), 'Vision Health', 'Evaluates overall eye function', 'Tracks contrast sensitivity, depth perception, and eye strain'),
  ('0029', 'physical', get_category_id('physical', 'Sensory Systems'), 'Hearing Health', 'Measures auditory processing ability', 'Determines hearing range and sound clarity'),
  ('002A', 'physical', get_category_id('physical', 'Sensory Systems'), 'Sensory Sensitivity', 'Assesses responsiveness to environmental stimuli', 'Tracks reactions to touch, light, and sound'),
  ('002B', 'physical', get_category_id('physical', 'Physical Response'), 'Physical Sensitivity', 'Evaluates body perception of environmental conditions', 'Measures awareness of temperature, texture, and pain'),
  ('002C', 'physical', get_category_id('physical', 'Physical Response'), 'Pain Sensitivity', 'Determines reaction to painful stimuli', 'Assesses individual pain threshold levels'),
  ('002D', 'physical', get_category_id('physical', 'Physical Response'), 'Temperature Sensitivity', 'Measures adaptation to hot and cold environments', 'Determines tolerance levels in extreme temperatures'),
  ('002E', 'physical', get_category_id('physical', 'Sensory Systems'), 'Light Sensitivity', 'Assesses visual discomfort from bright light', 'Determines potential for migraines or eye strain'),
  ('002F', 'physical', get_category_id('physical', 'Sensory Systems'), 'Sound Sensitivity', 'Measures response to noise levels', 'Identifies risk for auditory discomfort or hypersensitivity'),
  ('0030', 'physical', get_category_id('physical', 'Sensory Systems'), 'Touch Sensitivity', 'Evaluates reaction to physical contact', 'Assesses perception of pressure and texture'),
  ('0031', 'physical', get_category_id('physical', 'Sensory Systems'), 'Smell Sensitivity', 'Measures olfactory perception', 'Evaluates ability to detect and distinguish odors'),
  ('0032', 'physical', get_category_id('physical', 'Sensory Systems'), 'Taste Sensitivity', 'Assesses flavor distinction', 'Measures ability to identify different tastes'),
  ('0033', 'physical', get_category_id('physical', 'Physical Abilities'), 'Physical Activity Level', 'Tracks daily movement', 'Monitors overall physical activity and movement patterns'),
  ('0034', 'physical', get_category_id('physical', 'Physical Abilities'), 'Exercise Frequency', 'Measures workout habits', 'Tracks regularity of physical exercise'),
  ('0035', 'physical', get_category_id('physical', 'Physical Abilities'), 'Sport Participation', 'Evaluates engagement in sports', 'Measures involvement in athletic activities'),
  ('0036', 'physical', get_category_id('physical', 'Health Status'), 'Fitness Goals', 'Tracks fitness aspirations', 'Records personal fitness objectives and progress'),
  ('0037', 'physical', get_category_id('physical', 'Health Status'), 'Health Awareness', 'Measures attention to wellness', 'Evaluates knowledge of personal health status'),
  ('0038', 'physical', get_category_id('physical', 'Health Status'), 'Nutrition Awareness', 'Evaluates dietary knowledge', 'Assesses understanding of nutritional needs'),
  ('0039', 'physical', get_category_id('physical', 'Health Status'), 'Wellness Practices', 'Tracks mindfulness activities', 'Monitors engagement in health-promoting behaviors'),
  ('003A', 'physical', get_category_id('physical', 'Physical Abilities'), 'Physical Limitations', 'Assesses physical constraints or disabilities', 'Identifies movement restrictions and adaptations'),
  ('003B', 'physical', get_category_id('physical', 'Physical Abilities'), 'Mobility', 'Evaluates ease of movement and locomotion', 'Measures ability to move freely and independently'),
  ('003C', 'physical', get_category_id('physical', 'Physical Abilities'), 'Posture', 'Measures alignment and stance of the body', 'Evaluates spinal alignment and body positioning'),
  ('003D', 'physical', get_category_id('physical', 'Body Systems'), 'Joint Health', 'Assesses condition and functionality of joints', 'Tracks joint mobility and inflammation'),
  ('003E', 'physical', get_category_id('physical', 'Body Systems'), 'Tendon Health', 'Evaluates strength and flexibility of tendons', 'Measures tendon elasticity and injury risk'),
  ('003F', 'physical', get_category_id('physical', 'Physical Abilities'), 'DIY Skills', 'Measures ability to perform physical do-it-yourself tasks', 'Evaluates manual dexterity and tool usage'),

  -- Social World DNA attributes (0040-007F)
  ('0040', 'social', get_category_id('social', 'Social Activity'), 'Social Frequency', 'Measures how often the user engages in social interactions', 'Tracks the frequency of face-to-face and online communication'),
  ('0041', 'social', get_category_id('social', 'Social Activity'), 'Social Media Influencer', 'Assesses user influence in online communities', 'Evaluates social media reach, engagement, and follower interactions'),
  ('0042', 'social', get_category_id('social', 'Relationships'), 'Relationship Network', 'Measures the size and strength of social connections', 'Tracks friendships, professional relationships, and acquaintances'),
  ('0043', 'social', get_category_id('social', 'Relationships'), 'Family Bonding', 'Evaluates the quality of family relationships', 'Measures interaction frequency and emotional closeness'),
  ('0044', 'social', get_category_id('social', 'Relationships'), 'Friendship Level', 'Assesses the depth and stability of friendships', 'Tracks the number and duration of close friendships'),
  ('0045', 'social', get_category_id('social', 'Relationships'), 'Colleagues Relationship', 'Measures professional relationship quality', 'Evaluates teamwork, collaboration, and workplace communication'),
  ('0046', 'social', get_category_id('social', 'Relationships'), 'Romantic Relationship', 'Assesses relationship stability and satisfaction', 'Tracks relationship longevity and emotional bonding'),
  ('0047', 'social', get_category_id('social', 'Social Skills'), 'Social Skills', 'Measures the users ability to interact effectively with others', 'Evaluates communication, empathy, and adaptability'),
  ('0048', 'social', get_category_id('social', 'Social Skills'), 'Leadership Ability', 'Assesses the ability to influence and lead groups', 'Tracks leadership roles, decision-making, and team management skills'),
  ('0049', 'social', get_category_id('social', 'Social Skills'), 'Team Collaboration', 'Measures effectiveness in teamwork', 'Evaluates ability to cooperate, contribute, and resolve conflicts'),
  ('004A', 'social', get_category_id('social', 'Social Skills'), 'Conflict Resolution', 'Assesses ability to resolve interpersonal disputes', 'Evaluates communication strategies and negotiation skills'),
  ('004B', 'social', get_category_id('social', 'Social Skills'), 'Empathy Level', 'Measures understanding and sensitivity toward others emotions', 'Tracks ability to recognize and respond to emotional cues'),
  ('004C', 'social', get_category_id('social', 'Personality'), 'Humor Sense', 'Evaluates the users sense of humor', 'Measures the ability to engage in lighthearted interactions'),
  ('004D', 'social', get_category_id('social', 'Personality'), 'Extroversion', 'Assesses preference for social engagement', 'Tracks comfort level in group interactions and public settings'),
  ('004E', 'social', get_category_id('social', 'Personality'), 'Openness', 'Measures willingness to accept new experiences', 'Evaluates adaptability, curiosity, and interest in different perspectives'),
  ('004F', 'social', get_category_id('social', 'Personality'), 'Agreeableness', 'Assesses friendliness and cooperation', 'Measures politeness, kindness, and ability to maintain relationships'),
  ('0050', 'social', get_category_id('social', 'Personality'), 'Neuroticism', 'Evaluates emotional stability', 'Tracks stress levels, anxiety tendencies, and mood fluctuations'),
  ('0051', 'social', get_category_id('social', 'Personality'), 'Conscientiousness', 'Measures responsibility and discipline', 'Evaluates organization, planning, and goal-setting habits'),
  ('0052', 'social', get_category_id('social', 'Social Traits'), 'Social Anxiety', 'Assesses discomfort in social settings', 'Measures levels of nervousness or fear in interactions'),
  ('0053', 'social', get_category_id('social', 'Social Skills'), 'Public Expression', 'Evaluates comfort in speaking publicly', 'Measures ability to express opinions and ideas in groups'),
  ('0054', 'social', get_category_id('social', 'Participation'), 'Social Participation', 'Tracks involvement in social activities', 'Measures attendance at social events and community gatherings'),
  ('0055', 'social', get_category_id('social', 'Participation'), 'Volunteer Activity', 'Measures participation in unpaid, community-focused work', 'Tracks involvement in charities and local initiatives'),
  ('0056', 'social', get_category_id('social', 'Community'), 'Community Involvement', 'Evaluates engagement in local communities', 'Measures participation in neighborhood and civic events'),
  ('0057', 'social', get_category_id('social', 'Participation'), 'Cultural Participation', 'Assesses involvement in cultural and artistic events', 'Tracks attendance at museums, concerts, and festivals'),
  ('0058', 'social', get_category_id('social', 'Participation'), 'Political Involvement', 'Measures engagement in political activities', 'Tracks voting history, activism, and political discussions'),
  ('0059', 'social', get_category_id('social', 'Participation'), 'Religious Involvement', 'Assesses participation in religious practices', 'Measures frequency of worship, rituals, and faith-based activities'),
  ('005A', 'social', get_category_id('social', 'Participation'), 'Interest Group Participation', 'Measures activity in hobby or professional groups', 'Tracks involvement in clubs, societies, and special-interest groups'),
  ('005B', 'social', get_category_id('social', 'Social Traits'), 'Trust Level', 'Assesses general trust in people and institutions', 'Measures confidence in others and willingness to cooperate'),
  ('005C', 'social', get_category_id('social', 'Social Traits'), 'Social Support', 'Evaluates access to emotional and practical help', 'Tracks support received from family, friends, and community'),
  ('005D', 'social', get_category_id('social', 'Social Traits'), 'Social Isolation', 'Measures level of detachment from social activities', 'Tracks frequency of solitary activities and lack of engagement'),
  ('005E', 'social', get_category_id('social', 'Social Traits'), 'Social Focus', 'Evaluates the primary motivation for social interactions', 'Tracks whether interactions are driven by networking, friendships, or personal growth'),
  ('005F', 'social', get_category_id('social', 'Social Traits'), 'Social Motivation', 'Measures drive for forming relationships', 'Evaluates whether social interactions are purposeful or incidental'),
  ('0060', 'social', get_category_id('social', 'Social Traits'), 'Social Style', 'Assesses approach to socialization', 'Categorizes users as introverts, extroverts, or ambiverts'),
  ('0061', 'social', get_category_id('social', 'Social Dynamics'), 'Social Role', 'Evaluates typical role in social settings', 'Determines whether the user is a leader, supporter, or observer'),
  ('0062', 'social', get_category_id('social', 'Social Traits'), 'Social Preference', 'Measures preference for group vs. solo activities', 'Tracks likelihood of seeking companionship or solitude'),
  ('0063', 'social', get_category_id('social', 'Social Skills'), 'Social Adaptability', 'Assesses ability to adjust to new social environments', 'Measures flexibility in unfamiliar settings'),
  ('0064', 'social', get_category_id('social', 'Social Skills'), 'Social Innovation', 'Evaluates ability to introduce new social ideas', 'Tracks creativity in group settings'),
  ('0065', 'social', get_category_id('social', 'Social Skills'), 'Social Learning', 'Measures ability to gain knowledge from social experiences', 'Tracks how well users absorb new information through conversations'),
  ('0066', 'social', get_category_id('social', 'Social Skills'), 'Social Memory', 'Evaluates ability to remember social details', 'Tracks retention of names, dates, and personal facts'),
  ('0067', 'social', get_category_id('social', 'Social Skills'), 'Social Perception', 'Measures ability to interpret social cues', 'Tracks awareness of body language and tone of voice'),
  ('0068', 'social', get_category_id('social', 'Social Skills'), 'Social Response', 'Assesses reaction speed in conversations', 'Evaluates response time and fluency'),
  ('0069', 'social', get_category_id('social', 'Social Skills'), 'Social Expression', 'Measures ability to express emotions effectively', 'Tracks comfort in sharing thoughts and feelings'),
  ('006A', 'social', get_category_id('social', 'Social Dynamics'), 'Social Control', 'Evaluates ability to manage social interactions', 'Measures leadership skills and social dominance'),
  ('006B', 'social', get_category_id('social', 'Social Skills'), 'Social Creativity', 'Assesses ability to generate unique social ideas', 'Tracks originality in group dynamics'),
  ('006C', 'social', get_category_id('social', 'Social Skills'), 'Social Intelligence', 'Measures overall understanding of human interactions', 'Evaluates ability to navigate complex social scenarios'),
  ('006D', 'social', get_category_id('social', 'Social Traits'), 'Social Emotion', 'Assesses intensity of emotions in social settings', 'Tracks emotional reactivity in conversations'),
  ('006E', 'social', get_category_id('social', 'Social Dynamics'), 'Social Health', 'Measures overall well-being in social life', 'Evaluates emotional fulfillment and stress levels from social engagement'),
  ('006F', 'social', get_category_id('social', 'Social Dynamics'), 'Social Satisfaction', 'Assesses overall happiness with social life', 'Measures how fulfilling social interactions feel'),
  ('0070', 'social', get_category_id('social', 'Social Dynamics'), 'Social Goals', 'Evaluates clarity and direction of social ambitions', 'Tracks desire to build relationships or professional networks'),
  ('0071', 'social', get_category_id('social', 'Social Dynamics'), 'Social Achievements', 'Tracks accomplishments in social endeavors', 'Records successful social initiatives and milestones'),
  ('0072', 'social', get_category_id('social', 'Social Dynamics'), 'Social Challenges', 'Assesses difficulties faced in social interactions', 'Identifies areas for improvement in social skills'),
  ('0073', 'social', get_category_id('social', 'Social Dynamics'), 'Social Resources', 'Measures access to social networks and support systems', 'Evaluates available social connections and resources'),
  ('0074', 'social', get_category_id('social', 'Social Dynamics'), 'Social Support Received', 'Tracks the amount of support received from social connections', 'Measures help and assistance from social network'),
  ('0075', 'social', get_category_id('social', 'Social Dynamics'), 'Social Pressure', 'Evaluates stress experienced from social expectations', 'Tracks impact of social demands and obligations'),
  ('0076', 'social', get_category_id('social', 'Social Dynamics'), 'Social Balance', 'Measures equilibrium between social and personal life', 'Evaluates time management between social activities and personal needs'),
  ('0077', 'social', get_category_id('social', 'Social Skills'), 'Language Proficiency', 'Assesses ability to communicate in multiple languages', 'Tracks multilingual communication skills'),
  ('0078', 'social', get_category_id('social', 'Social Skills'), 'Cross-Cultural Communication', 'Evaluates effectiveness in interacting across cultures', 'Measures cultural sensitivity and adaptation'),
  ('0079', 'social', get_category_id('social', 'Social Skills'), 'Social Etiquette', 'Measures adherence to social norms and manners', 'Tracks appropriate behavior in various social contexts'),
  ('007A', 'social', get_category_id('social', 'Social Skills'), 'Online Etiquette', 'Assesses politeness and behavior in digital interactions', 'Evaluates appropriate online communication'),
  ('007B', 'social', get_category_id('social', 'Social Skills'), 'Referral Persuasion', 'Evaluates ability to convince others to join social initiatives', 'Measures success in expanding social networks'),
  ('007C', 'social', get_category_id('social', 'Community'), 'Community Leader', 'Assesses leadership within a community setting', 'Tracks influence and guidance in community groups'),
  ('007D', 'social', get_category_id('social', 'Social Activity'), 'Social Media Engagement', 'Measures activity and interaction on social media platforms', 'Evaluates online social presence and participation'),
  ('007E', 'social', get_category_id('social', 'Community'), 'Field Leader', 'Evaluates leadership in a specific domain or interest area', 'Tracks expertise and influence in specialized communities'),
  ('007F', 'social', get_category_id('social', 'Community'), 'Empathy Evangelist', 'Assesses efforts to promote empathy in social contexts', 'Measures advocacy for emotional understanding'),

  -- Digital World DNA attributes (0080-00BF)
  ('0080', 'digital', get_category_id('digital', 'Online Activity'), 'Internet OG Sharing', 'Measures user engagement in sharing original content online', 'Tracks posting frequency and originality of digital content'),
  ('0081', 'digital', get_category_id('digital', 'Digital Skills'), 'Digital Literacy', 'Evaluates ability to understand and use digital technology', 'Measures proficiency in navigating online platforms, software, and tools'),
  ('0082', 'digital', get_category_id('digital', 'Digital Skills'), 'Stock Investment Winner', 'Assesses success in stock market investments', 'Tracks historical performance in trading and investment strategies'),
  ('0083', 'digital', get_category_id('digital', 'Gaming'), 'Game Achiever', 'Measures accomplishment levels in gaming activities', 'Evaluates success in completing missions, ranking systems, and competitive play'),
  ('0084', 'digital', get_category_id('digital', 'Gaming'), 'Texas Holdem Hero', 'Assesses skill level in Texas Holdem poker', 'Tracks winning rate, strategic decision-making, and tournament performance'),
  ('0085', 'digital', get_category_id('digital', 'Gaming'), 'Mahjong Hero', 'Measures expertise in Mahjong strategy and gameplay', 'Evaluates pattern recognition, risk assessment, and competition results'),
  ('0086', 'digital', get_category_id('digital', 'Gaming'), 'Game Skill Hero', 'Evaluates general gaming proficiency', 'Measures reaction time, strategy, and adaptability across different games'),
  ('0087', 'digital', get_category_id('digital', 'Digital Skills'), 'Cybersecurity Awareness', 'Assesses knowledge and practices regarding online security', 'Tracks safe browsing habits, password management, and phishing resistance'),
  ('0088', 'digital', get_category_id('digital', 'Development'), 'Programming Level', 'Evaluates coding skills in software development', 'Measures proficiency in multiple programming languages and debugging ability'),
  ('0089', 'digital', get_category_id('digital', 'Web3'), 'Chain Adaptability', 'Measures ability to navigate blockchain technologies', 'Tracks engagement with smart contracts, DeFi, and NFT marketplaces'),
  ('008A', 'digital', get_category_id('digital', 'Technical'), 'Virtual Reality Experience', 'Assesses familiarity with VR environments', 'Tracks frequency of VR interaction and level of immersion'),
  ('008B', 'digital', get_category_id('digital', 'Technical'), 'Augmented Reality Proficiency', 'Evaluates experience with AR applications', 'Measures skill in using and creating AR content'),
  ('008C', 'digital', get_category_id('digital', 'Online Activity'), 'Digital Content Consumption', 'Measures frequency of digital media consumption', 'Tracks time spent watching videos, reading articles, and engaging in online education'),
  ('008D', 'digital', get_category_id('digital', 'Digital Skills'), 'Digital Marketing Skills', 'Assesses expertise in digital marketing strategies', 'Evaluates proficiency in SEO, PPC advertising, and social media outreach'),
  ('008E', 'digital', get_category_id('digital', 'Online Activity'), 'Online Learning Engagement', 'Measures participation in digital education', 'Tracks enrollment in courses, certifications, and self-learning practices'),
  ('008F', 'digital', get_category_id('digital', 'Technical'), 'Cloud Computing Usage', 'Evaluates reliance on cloud-based services', 'Measures use of storage, computing power, and cloud-based applications'),
  ('0090', 'digital', get_category_id('digital', 'Digital Skills'), 'Digital Content Creation', 'Assesses ability to create and distribute digital content', 'Tracks blog posts, video production, and online artworks'),
  ('0091', 'digital', get_category_id('digital', 'Digital Skills'), 'E-Commerce Expertise', 'Evaluates ability to operate in online marketplaces', 'Tracks experience in dropshipping , selling products, and managing digital storefronts'),
  ('0092', 'digital', get_category_id('digital', 'Development'), 'User Experience Empathy', 'Measures ability to understand user needs in digital interfaces', 'Evaluates UX design skills and user-centered design approach'),
  ('0093', 'digital', get_category_id('digital', 'Development'), 'Engineering Developer', 'Assesses engineering knowledge in digital technology', 'Tracks experience in software and hardware engineering'),
  ('0094', 'digital', get_category_id('digital', 'Development'), 'Digital Devices Developer', 'Measures ability to create and modify digital devices', 'Tracks proficiency in IoT development, circuit design, and hardware programming'),
  ('0095', 'digital', get_category_id('digital', 'Web3'), 'Metaverse Navigator', 'Assesses skill in operating within metaverse environments', 'Tracks engagement in virtual worlds and digital identity management'),
  ('0096', 'digital', get_category_id('digital', 'Technical'), 'AI Trainer', 'Evaluates expertise in training artificial intelligence models', 'Measures contributions to AI dataset labeling, tuning, and automation'),
  ('0097', 'digital', get_category_id('digital', 'Digital Identity'), 'Oxer Data Complete Level', 'Assesses how complete a users digital profile is', 'Measures the accuracy and depth of provided personal and behavioral data'),
  ('0098', 'digital', get_category_id('digital', 'Digital Identity'), 'Oxer Referral Score', 'Measures effectiveness of referring others to digital platforms', 'Tracks how many referrals result in active engagement'),
  ('0099', 'digital', get_category_id('digital', 'Web3'), 'Web3 Knowledge Level', 'Assesses understanding of Web3 technologies', 'Evaluates familiarity with decentralized protocols, DAOs, and smart contracts'),
  ('009A', 'digital', get_category_id('digital', 'Web3'), 'Blockchain Understanding', 'Measures depth of knowledge in blockchain technology', 'Tracks users ability to analyze, audit, and implement blockchain solutions'),
  ('009B', 'digital', get_category_id('digital', 'Crypto'), 'Cryptocurrency Trader', 'Evaluates experience and success in crypto trading', 'Tracks portfolio performance, risk management, and transaction volume'),
  ('009C', 'digital', get_category_id('digital', 'Web3'), 'DAO Participation', 'Assesses level of involvement in decentralized autonomous organizations', 'Measures voting activity, governance proposal contributions, and token holding'),
  ('009D', 'digital', get_category_id('digital', 'Crypto'), 'NFT Curator', 'Evaluates participation in NFT collecting and trading', 'Tracks users NFT portfolio diversity and trading activity'),
  ('009E', 'digital', get_category_id('digital', 'Crypto'), 'Crypto Wealth', 'Measures the amount of crypto assets held', 'Assesses overall financial position in digital currencies'),
  ('009F', 'digital', get_category_id('digital', 'Crypto'), 'Gas Contributor', 'Evaluates transaction contributions to blockchain gas fees', 'Tracks frequency and cost of blockchain interactions'),
  ('00A0', 'digital', get_category_id('digital', 'Crypto'), 'Airdrop Diamond Hand', 'Assesses ability to hold onto airdrop tokens over time', 'Measures retention and sale timing of received assets'),
  ('00A1', 'digital', get_category_id('digital', 'Web3'), 'Web3 Social Networking', 'Evaluates engagement in Web3-based social platforms', 'Tracks participation in decentralized networking applications'),
  ('00A2', 'digital', get_category_id('digital', 'Crypto'), 'Blockchain Profit Exploring', 'Measures success in finding blockchain-based profit opportunities', 'Tracks history of arbitrage, DeFi farming, and yield generation'),
  ('00A3', 'digital', get_category_id('digital', 'Crypto'), 'Meme Coin Digger', 'Assesses ability to identify and profit from meme coins', 'Tracks entry timing, holding duration, and overall return'),
  ('00A4', 'digital', get_category_id('digital', 'Crypto'), 'Crypto Winners', 'Measures success rate in crypto investments', 'Tracks past transaction history and profitability'),
  ('00A5', 'digital', get_category_id('digital', 'Web3'), 'Smart Contract Explorer', 'Assesses ability to analyze and interact with smart contracts', 'Tracks use of blockchain scanners and participation in contract testing'),
  ('00A6', 'digital', get_category_id('digital', 'Web3'), 'DeSoc Participation', 'Measures engagement in decentralized social platforms', 'Evaluates activity levels on decentralized social media'),
  ('00A7', 'digital', get_category_id('digital', 'Development'), 'Web3 Development Skills', 'Assesses technical ability in Web3 coding and architecture', 'Measures smart contract writing, front-end interaction, and API integration'),
  ('00A8', 'digital', get_category_id('digital', 'Digital Identity'), 'Web3 Testimonials', 'Measures credibility in Web3 contributions', 'Tracks received endorsements and reviews'),
  ('00A9', 'digital', get_category_id('digital', 'Digital Identity'), 'Oxer Outer Score', 'Evaluates external reputation score in digital spaces', 'Measures credibility based on online activities and community engagement'),
  ('00AA', 'digital', get_category_id('digital', 'Web3'), 'DAO Leader', 'Assesses leadership role in DAOs', 'Tracks governance proposal history and decision-making influence'),
  ('00AB', 'digital', get_category_id('digital', 'Digital Skills'), 'Referral Persuasion Skills', 'Evaluates effectiveness in convincing others to join digital initiatives', 'Measures success rate in onboarding new users'),
  ('00AC', 'digital', get_category_id('digital', 'Digital Skills'), 'Communication Skills', 'Measures effectiveness in digital interactions', 'Evaluates clarity, influence, and responsiveness in online discussions'),
  ('00AD', 'digital', get_category_id('digital', 'Digital Identity'), 'Social Media Influencer', 'Assesses influence on social media platforms', 'Measures reach, engagement, and impact on followers'),
  ('00AE', 'digital', get_category_id('digital', 'Digital Identity'), 'Field Leader', 'Evaluates leadership in a specific digital domain', 'Tracks expertise and influence in specialized digital communities'),
  ('00AF', 'digital', get_category_id('digital', 'Digital Identity'), 'Research Impactor', 'Measures influence of research contributions in digital spaces', 'Evaluates citations, references, and knowledge sharing'),
  ('00B0', 'digital', get_category_id('digital', 'Digital Identity'), 'Empathy Evangelist', 'Assesses efforts to promote empathy in digital communities', 'Measures advocacy for understanding in online spaces'),
  ('00B1', 'digital', get_category_id('digital', 'Digital Identity'), 'Trend Setter', 'Evaluates ability to establish trends in digital environments', 'Tracks influence on digital culture and behavior'),
  ('00B2', 'digital', get_category_id('digital', 'Web3'), 'Web3 Community Leader', 'Assesses leadership within Web3 communities', 'Measures influence and guidance in decentralized spaces'),
  ('00B3', 'digital', get_category_id('digital', 'Crypto'), 'Blockchain Profit Index', 'Measures profitability from blockchain activities', 'Evaluates overall return on blockchain investments'),
  ('00B4', 'digital', get_category_id('digital', 'Crypto'), 'Meme Coin Participation', 'Tracks engagement with meme coin ecosystems', 'Measures involvement in meme coin communities'),
  ('00B5', 'digital', get_category_id('digital', 'Crypto'), 'Crypto OG Level', 'Assesses experience as an early adopter in cryptocurrency', 'Evaluates long-term participation in crypto markets'),
  ('00B6', 'digital', get_category_id('digital', 'Web3'), 'Web3 Activation Level', 'Measures activity level in Web3 ecosystems', 'Tracks overall engagement with decentralized platforms'),
  ('00B7', 'digital', get_category_id('digital', 'Development'), 'Blockchain Engineering', 'Evaluates technical skills in blockchain development', 'Measures ability to build and maintain blockchain systems'),
  ('00B8', 'digital', get_category_id('digital', 'Development'), 'DAPP Proficiency', 'Assesses expertise in decentralized application usage and development', 'Evaluates ability to create and interact with DAPPs'),
  ('00B9', 'digital', get_category_id('digital', 'Web3'), 'DAO Participation Index', 'Measures overall engagement level in DAOs', 'Tracks voting, proposal, and governance activities'),
  ('00BA', 'digital', get_category_id('digital', 'Web3'), 'NFT Participation', 'Tracks involvement in NFT creation, trading, or collection', 'Measures engagement with NFT ecosystems'),
  ('00BB', 'digital', get_category_id('digital', 'Web3'), 'DeFi Participation', 'Measures engagement in decentralized finance activities', 'Tracks usage of DeFi protocols and services'),
  ('00BC', 'digital', get_category_id('digital', 'Digital Skills'), 'Digital Privacy Awareness', 'Evaluates knowledge of protecting personal data online', 'Measures understanding of privacy best practices'),
  ('00BD', 'digital', get_category_id('digital', 'Digital Skills'), 'Data Security Practices', 'Assesses habits for securing digital information', 'Evaluates implementation of security measures'),
  ('00BE', 'digital', get_category_id('digital', 'Digital Skills'), 'Password Strength', 'Measures the robustness of user passwords', 'Evaluates password complexity and security'),
  ('00BF', 'digital', get_category_id('digital', 'Digital Skills'), 'Two-Factor Authentication', 'Evaluates use of two-factor authentication for security', 'Tracks implementation of additional security layers'),

  -- Spiritual World DNA attributes (00C0-00FF)
  ('00C0', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Religion', 'Measures the users level of religious belief and practice', 'Tracks engagement in religious activities, rituals, and faith-based community involvement'),
  ('00C1', 'spiritual', get_category_id('spiritual', 'Intelligence'), 'MBTI', 'Assesses personality type based on MBTI classification', 'Categorizes users into 16 personality types, influencing decision-making and social interactions'),
  ('00C2', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Lifestyle Attitudes', 'Evaluates mindset toward life choices and habits', 'Measures openness to change, risk-taking, and work-life balance'),
  ('00C3', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Astrology', 'Measures interest in astrology and celestial influences', 'Tracks engagement in zodiac readings, astrological beliefs, and horoscope consultations'),
  ('00C4', 'spiritual', get_category_id('spiritual', 'Intelligence'), 'Intelligence Quotient', 'Assesses cognitive ability based on problem-solving and reasoning', 'Evaluates logical reasoning, memory, and analytical skills'),
  ('00C5', 'spiritual', get_category_id('spiritual', 'Intelligence'), 'Personality Traits', 'Measures distinct psychological characteristics shaping user behavior', 'Tracks tendencies like introversion, extroversion, and adaptability'),
  ('00C6', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Emotional Intelligence', 'Evaluates ability to understand, manage, and express emotions', 'Measures empathy, self-awareness, and interpersonal communication'),
  ('00C7', 'spiritual', get_category_id('spiritual', 'Intelligence'), 'Technical Aptitude', 'Assesses natural skill in learning and using technology', 'Evaluates ease of adapting to new software, hardware, and technical concepts'),
  ('00C8', 'spiritual', get_category_id('spiritual', 'Spiritual Practice'), 'Mindfulness', 'Measures ability to maintain awareness of the present moment', 'Tracks meditation practices, stress management, and focus improvement techniques'),
  ('00C9', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Gratitude Level', 'Evaluates how often and deeply the user experiences gratitude', 'Tracks expressions of thankfulness and appreciation in daily life'),
  ('00CA', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Purpose in Life', 'Assesses clarity and commitment to personal goals', 'Evaluates self-direction and long-term aspirations'),
  ('00CB', 'spiritual', get_category_id('spiritual', 'Growth'), 'Self-Awareness', 'Measures ability to recognize and understand personal emotions', 'Tracks reflection habits and self-improvement efforts'),
  ('00CC', 'spiritual', get_category_id('spiritual', 'Spiritual Practice'), 'Spiritual Practices', 'Evaluates engagement in spiritual activities', 'Tracks meditation, prayer, yoga, and other faith-based rituals'),
  ('00CD', 'spiritual', get_category_id('spiritual', 'Spiritual Practice'), 'Meditation Depth', 'Assesses proficiency in meditation techniques', 'Measures mindfulness, focus duration, and depth of relaxation'),
  ('00CE', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Spiritual Connection', 'Measures personal connection to higher consciousness or beliefs', 'Tracks religious faith, existential exploration, and philosophical alignment'),
  ('00CF', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Inner Peace', 'Assesses the users state of emotional and mental tranquility', 'Measures resilience against stress and anxiety'),
  ('00D0', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Resilience', 'Evaluates ability to recover from setbacks', 'Tracks coping mechanisms and emotional endurance'),
  ('00D1', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Hope', 'Measures optimism for future events and outcomes', 'Evaluates positive expectations and goal-oriented mindset'),
  ('00D2', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Optimism', 'Assesses general outlook on life', 'Tracks tendencies toward positivity or negativity in thinking patterns'),
  ('00D3', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Self-Esteem', 'Measures confidence and self-worth', 'Evaluates how the user perceives their own value and achievements'),
  ('00D4', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Life Satisfaction', 'Assesses overall contentment with life experiences', 'Tracks happiness in personal, professional, and social aspects'),
  ('00D5', 'spiritual', get_category_id('spiritual', 'Growth'), 'Personal Growth', 'Evaluates commitment to self-improvement', 'Measures engagement in skill-building, education, and reflection'),
  ('00D6', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Altruism', 'Measures willingness to help others without expectation of return', 'Tracks charitable giving, volunteering, and social responsibility'),
  ('00D7', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Forgiveness', 'Evaluates ability to let go of past grievances', 'Measures openness to reconciliation and emotional release'),
  ('00D8', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Compassion', 'Assesses concern and empathy toward others suffering', 'Tracks supportive behaviors and emotional sensitivity'),
  ('00D9', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Faith in Humanity', 'Measures trust in human kindness and goodness', 'Evaluates belief in moral integrity and social cooperation'),
  ('00DA', 'spiritual', get_category_id('spiritual', 'Growth'), 'Spiritual Exploration', 'Evaluates curiosity about spiritual and existential topics', 'Tracks engagement in philosophy, metaphysics, and consciousness studies'),
  ('00DB', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Ethical Values', 'Assesses strength of moral and ethical principles', 'Measures consistency in honesty, fairness, and justice'),
  ('00DC', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Moral Integrity', 'Evaluates alignment between personal values and actions', 'Tracks adherence to ethical beliefs in daily life'),
  ('00DD', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Spiritual Awakening', 'Measures level of self-discovery and spiritual realization', 'Tracks transformative life experiences and deepened awareness'),
  ('00DE', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Transcendence', 'Evaluates feelings of connection beyond personal identity', 'Measures ability to experience moments of awe and oneness with the universe'),
  ('00DF', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Enlightenment', 'Assesses level of profound understanding and wisdom', 'Tracks insights into human nature, life purpose, and interconnectedness'),
  ('00E0', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Karma Balance', 'Evaluates alignment of actions with expected consequences', 'Measures belief in cause and effect in moral choices'),
  ('00E1', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Dharma Alignment', 'Assesses alignment with personal or spiritual duty', 'Tracks adherence to principles guiding ethical and purposeful living'),
  ('00E2', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Soul Purpose', 'Measures clarity of life mission and direction', 'Evaluates spiritual and professional aspirations'),
  ('00E3', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Cosmic Awareness', 'Assesses recognition of self in relation to the universe', 'Measures understanding of cosmic principles and existential philosophy'),
  ('00E4', 'spiritual', get_category_id('spiritual', 'Spiritual Practice'), 'Mystical Experiences', 'Evaluates encounters with transcendent or supernatural phenomena', 'Tracks meditation insights, near-death experiences, or paranormal awareness'),
  ('00E5', 'spiritual', get_category_id('spiritual', 'Spiritual Practice'), 'Divine Connection', 'Measures perceived relationship with divine entities', 'Evaluates prayer frequency, religious visions, and spiritual presence'),
  ('00E6', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Health', 'Assesses overall well-being in spiritual aspects of life', 'Tracks emotional fulfillment derived from spiritual practices'),
  ('00E7', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Faith Strength', 'Measures commitment to personal or religious beliefs', 'Evaluates consistency of faith-based actions'),
  ('00E8', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Joy', 'Assesses fulfillment and happiness derived from spirituality', 'Tracks sense of purpose and peace'),
  ('00E9', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Serenity', 'Measures ability to remain calm in difficult situations', 'Evaluates emotional stability and mindfulness'),
  ('00EA', 'spiritual', get_category_id('spiritual', 'Growth'), 'Spiritual Purpose', 'Evaluates understanding of ones reason for existence', 'Tracks clarity in life goals and service to others'),
  ('00EB', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Universal Love', 'Measures compassion toward all living beings', 'Evaluates connection to humanity, nature, and the cosmos'),
  ('00EC', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Higher Consciousness', 'Assesses awareness beyond ordinary perception', 'Tracks deep states of intuition and spiritual insight'),
  ('00ED', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Fulfillment', 'Evaluates satisfaction with ones spiritual journey', 'Measures sense of completeness and divine connection'),
  ('00EE', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Inner Harmony', 'Assesses emotional and spiritual balance', 'Tracks ability to maintain peace in adversity'),
  ('00EF', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Universal Understanding', 'Measures comprehension of lifes greater meaning', 'Evaluates wisdom and interconnectedness with existence'),
  ('00F0', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Resilience', 'Evaluates ability to maintain spiritual strength in adversity', 'Measures persistence in spiritual practices during challenges'),
  ('00F1', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Spiritual Hope', 'Measures optimism rooted in spiritual beliefs', 'Evaluates faith-based confidence in future outcomes'),
  ('00F2', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Spiritual Optimism', 'Assesses positive outlook influenced by spirituality', 'Tracks spiritual influence on life perspective'),
  ('00F3', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Self-Esteem', 'Measures confidence derived from spiritual identity', 'Evaluates self-worth based on spiritual values'),
  ('00F4', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Satisfaction', 'Assesses contentment with spiritual life', 'Measures fulfillment in spiritual journey'),
  ('00F5', 'spiritual', get_category_id('spiritual', 'Growth'), 'Spiritual Growth', 'Evaluates progress in spiritual development', 'Tracks advancement in spiritual understanding'),
  ('00F6', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Spiritual Altruism', 'Measures selfless acts motivated by spiritual beliefs', 'Evaluates service to others based on spiritual values'),
  ('00F7', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Spiritual Forgiveness', 'Evaluates forgiveness influenced by spiritual values', 'Measures ability to forgive through spiritual perspective'),
  ('00F8', 'spiritual', get_category_id('spiritual', 'Emotional'), 'Spiritual Compassion', 'Assesses empathy driven by spiritual principles', 'Evaluates care for others based on spiritual beliefs'),
  ('00F9', 'spiritual', get_category_id('spiritual', 'Beliefs'), 'Faith in Universe', 'Measures trust in the order and goodness of the universe', 'Evaluates belief in cosmic harmony'),
  ('00FA', 'spiritual', get_category_id('spiritual', 'Growth'), 'Spiritual Curiosity', 'Evaluates interest in exploring spiritual concepts', 'Measures desire to learn about spiritual matters'),
  ('00FB', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Ethical Leadership', 'Assesses leadership guided by ethical and spiritual principles', 'Evaluates moral influence on others'),
  ('00FC', 'spiritual', get_category_id('spiritual', 'Mindset'), 'Moral Courage', 'Measures bravery in upholding moral values', 'Evaluates strength in ethical decision-making'),
  ('00FD', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Spiritual Integrity', 'Evaluates consistency between spiritual beliefs and actions', 'Measures alignment of behavior with spiritual values'),
  ('00FE', 'spiritual', get_category_id('spiritual', 'Consciousness'), 'Universal Harmony', 'Assesses sense of unity and peace with the universe', 'Evaluates feeling of oneness with existence'),
  ('00FF', 'spiritual', get_category_id('spiritual', 'Inner State'), 'Life Satisfaction', 'Assesses overall happiness influenced by spiritual and worldly factors', 'Measures contentment with life through spiritual lens')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  definition = EXCLUDED.definition,
  description = EXCLUDED.description;